!include ./style.iuml

' Based on https://cncf-branding.netlify.app/projects/prometheus/

sprite $prometheus [256x256/16z] {
xPtNOeIy3eJLfVT_uTFxCRlye34soNUR0YEDvBe9pUENNtxvXLb4rSp_XPcg2FFhTPj7VIB3LFY5qiMypfF-eYY8HbqXNNbxxHPrYurZmEhLGPhiA3wg4PVT
nBUpZGl42qCQq-gmPG49MJtrQ5AP5aMpfc2yjdeypckhn-Fy3lK9ZC3wwaDiUm_8zTmhKTOTZ9w6lQuIJCHrZnHw5AlBE16Hrbs2LxV-c1Z4xngsjlN79FqD
hmPILax-6A6_4TM2qNIyvOMZUaZPAVcLDD2_aGMixg435-qp473KFP80-gk4fY1LNUadhKviEU-F6SIoXo0utfechbwI2GfdSvrcDIFWOQ-1GJKreWH3gmCV
DzFrkw0Y4fJLZXC4WrIeLJ-1QVnDq7_11I1uNVb9_qryqh7CEEWmSqeTuhBAHC21tIcF8wMBp8GSEJpfSQ7O6bD1nyvFQepSV702v4Ccg7RearXX6BG2w-V3
xEK2ym35Br3ywDiMc0bANILgoA0jyT6RFxyMuBeCQusW0N4GfRgDFhVU5vAp-lN0k8_l1yIzqClPKGbuFC9FZNmsx1vnva7PEFB6KwtV3fmzGiPLQuzk1qX7
x_Lp7Jc7djL7TyIoGp_bgPUnOSRaoJrHhnRzUkfTP1WZhXPoMl6FLCIfTfp3xyd7TWIvxg934vzOPKJ_qakX8_yO6IKnJpHR0om-UFwYZqSYd8uOjWX-Q4jO
wZv34NR2S3TjE4Pd3dt7LIpV-srYLjyyqVt7LSpV6wvXZWTyOky_hc8wPkpKgFaL4Dr-opDjo8Sb8jL5Jjtnof6qiXEFFT6Ai9j1sVumFJCJbt6QhD0j4F90
6JOK-iIuJp7wN1Zpl65lYnE-K-3-kqmxxV1XIUc99mlX393JqY_3eFA9lil8yoUTbFvn4uipaswY9mqWcA56pqIV1sy8DG3kKJnExHS67fbi00ODD7ng_X63
Rvfh04UUyVEPtgCqoG38vmp7TZiryHRq6RpYq-z3QpDzGuvDaZCCmCWZVgLJ-ccCpfW4AYx26lGT_f2TdB0AIDmwKvXEyE7b5ByCbCUlu0zYDt4V843sFq-M
qWG3OBkVqsMYXD06W8-nGfVnOffWW836b-aozkc76Ti1fHulVzAQSmzLWVQtE_gJ3i1lXQ_m0JHnmCRq2CO5bsuWDkaghi7i7tG3Lle40miWb_Zu8TD31S1z
lnY8LHUA-is4H61Je01CVW6Wfa0Cy1M20Aq1PDdonu-0wvS_VWgOovK_VWs4ANymc6rG0VpIrHkWBLt--3Lm0gAQXCOWku2rOFl3duDisFv8gWs5jh_rzHlY
bZqQGTo6yttqS_NHlwr0M-ddxlQVU-aNv8TCrg__qX-ktxf_fw-kV_owkb7-jVe7GDj8lrKZW3_jXSO1-gEw83XP_HE0t4X_0VHt_a8mN9r8jtubCBAsVjkg
_PS2BbTZ2QZ-zHj0BQvVToh_idRzGL0Cgd_z0iZbzIlM_ilhJm9Yw-il8HorWVuW60hLlxu1SWlzWUj-tHYah6INz9T2zETJrPynHp-Jg6STelFJdwPCfDUS
cfT-Z4Mznl3Cz8Sfqz-9Q_hZ-YgVnM9A2-InTE73xpcltsyMEAibkW9i9Fr_i8kB5MleyF_J4XYN_dGLfX5vKRzsdNEng2Ua0dmW_VxyWAxe7wVtVrk2KIVo
FzA7-5Nzqh_FoSBK24EsnkFwfZgjXrq_hiPlSonvCSHkpAnVaFwI6uUgjd_wIsx4hdZxz1VVsLZnxTDVztvQQ27ytaODTfy7ZzmyhCtr3dlnMqCwiC-UBT3k
lhxMpXN0TOb1_UnP0N4_UxYjNZpMaBn0RVNYaOxS6V36xwB_aPixWbYwNV6FhLkrPmlmfgjgqF-qk-AHi7JzebYzzutfkrZgEygFnjDLsslUr_zNvdNbaMyC
jzukIDFPc3UVqTTFGg6NozQ76vhfnYGDo1zb_nzT0Dmmd6vCD2obTaQWzqlNXmwedu51xvUl3xSlAC8V0B1UZRw8uW7iMCaFq9_qWNY_VgKFoElr9tqatwvV
wIFwSlr9NyXtwrVwWhvQVz9NyitwbRuYBzQVT89uhtwX4yXhzGUTmlVG3qiJlrI_qKdqbVgJJfDlrAzq6dcX_Y0wZs-W7vgZV9j-HLwj49eFOs_fUAqEsA5P
BqAHbulMnv7tYjSdeLTBrqUG5wpMn-WYylxYVtyBIBg1ltpaVtyFb0SlcIfteA293xu7okFNd8rk8zE3lzZLV0L57v-0e1RiqV2JWEJZ0v3FFfsf2t_oNaoW
vEC3eDG0J3u-084jVxpy1Vv4GE3aumDWpup-GG3i4GCuKZu-0FP0zJk1qFa6I6p8yTc8sPRJnJvpQNFZBGI5Os92637kpM_8EiriJXFGIG7Wn3zdtelXdv92
it1y4nIaz-VNG31uu5EQ2WVo1Ja0uNrwDXo2JFvyE30Hq0Ga7u9MUmHO0OCB3BwmEZMXGyJhZ-9CJo9vPO6gF8YbUFNx2O_M9T9DHVYlYAZvbJYcqWAmBN-f
2zy6vcEq4EpxgDy_0gcq86oBgyUZMMXSQ6Ka2aWQq-gm9JRrwoDMxOJIJeXN8wvCso6MFJKlj2kiZa_y-Z78ka1kh7tyZz5E4wP2xuE_hdF3JONfvJ2BgAhz
2rKHuPcwV_dbbrz--JC
}

!define Prometheus(alias) Prometheus(alias,"")
!define Prometheus(alias, label)  PrometheusEntity(alias, "\nlabel", $prometheus,  Prometheus)
