!include ../style.iuml

sprite $control [256x248/16z] {
xDR5WKKn34FHIM9I_mKFCxFUbtCwaBsvP_zksxPjsyQbhjjNuaPvmniu7glPUFsrMdtM1rxLum8Zy2RJNvzubxTTht-1MVYK68tNNqkv2wp2jPuNMFYwb4aY
m_VKRBPUC0eTFxJ4GlVhJ31qzIym4h_8XTRhNs0M_a0ClTGZH25nlVu55ZvDC0eD_w6Mm7gv2pZ-rH9DlSypWVKA5nW96XT8FK8K4jPpBy1FFRqeN3YEd9tM
yxFOS3or2AdNy0AE0rlarECpSkhnENazdvDJZoy6Upt_0hpGrShYKJXHmMqzlXhStE4RXEyB7M3Yr5qmTwNxQyGWy4Su-_uFtBlTln8LDndShptSG9Z9p0On
bkA7SxJ0HPLU4ln7tp_fTH40ZLuEaebh5W032_zmgl0Cd8uVXaqRdHfpNApyRRwWuHS307KRas4OfhaG_3L7Zy_0PU2lzBhez38d82Zw_Wp85U2ldzDT_d7j
7-zkWSJ72K01qGCo02E0-FIr3CT7hqLWqVTdm03m1qIF4uLdy8UBlZy30FWZMAyk2l4M21XzVmQqMVs4NElYEO3c1nzzbiLu0Z10z80Cm1JG9PjGIDii43Jw
_WmuGFq0AX-N0PpvwUz6LZm1nALxiKdH5kZgNSWKK0iq-lhkXd3BnJJoqsF5tMHofj8E8UFt9kpBf5L7QiTe82rGqmsJvlPjyY9S3SZFX5RN-J76zAkgjSnN
0hH0311NXJJ7E_j5G08mcBYkOpXs4m3Xu8yGSh6R00GM_uO6Yp1LYxVuIc0MQ23Xdp5yT0IGH4vgFm5esrSEydUNB6r_Fm444Fvv2trQrcF_Aof6mNy9_p6l
Fe05C8pwyJKZF-RY-uCMGBgCFyqtPLJN2ehVkxolFS2v5ydACJe5fwjodSMZln30Up15m3-Mn9yz0hO3220GviUMhlRruGumb03wpK-6xlFuW_OJ05t5_5Y2
P4PWZEq485THF_5KF71rkGomG2tcnv-cJp_v3aIHwYTp33_r7n-mGD6XVkHP_KXQBzW2zQiVIfmq_RlOJG1s5VLZZ_V4qt8x2K2s9bGZZES9Y6ynIm3vMsTh
x8xVTvwe-k8W9ucxorEEbDoj130wrGyLG29VRpyaRh15-z-1AFZcXwQRG-zGM0Zz-g0n41VL0RtvqPkhJAwXZkixXBT0jb9EVeDshZxKooSqtWAjw0dxyZQV
nCj5DyfyYhT02zcKqw2xmHCB8_jKVIUTH74ddhGrn_XQm_odY8m-H02we7xutQApVpdKOt5SLZuG2nGhOFBt7gh_EPIFV7ekKxW5MbS_MJk43Y8Q6adAv6ST
CT38o09O89JwqKaRCCSZ3HnV3j4XPgPqRARXlgY0QtiRn-8pB49LLSUCQqRUIyQrgkuJ4pOlQQtfct7aSPGK4zu2hMg9H5rvXtoQ5rSHZNEN2h9D0T5Y9Ybp
VQOegYnSWBswiOrAfpkXBt35bOKBtWAj8ycdOOuN9IgL-1LlWTOJgTCeNm6BA_KVI0l46FhZ9y9jpd-5t7PQeB52V-oPkVC9u3m5HPWmirXCDebuD2aWEVyn
7C-J-ry43igxfdI4edSLm9O-4sQ1udGPZLV8_LiQ8twDVACRq2ezGhEfHK83m0Ajq5zce8V8YlyP3lT3-fM-saE0by2hCE9v_Fo8eMMoJgVQWIODZN1y7aMI
OP6HHJckg9xerg20_Fo7q7DqwTzOg-DPCmIyeH5kvHJr55KgJyy0ut95C-0by2ByxU661SrcPqSwOAnAwI4D5eZNSaX4D2GogVF15-JbkqDAqQC9G1SmbFRD
HfxUOeTAJ00gT8W15T1w2lEwmrJKSiQE6f2Ig1UC1SAvw7Y5Edtd9iwxBD1O-8Ig6EERmw9KqWmQru3xEYMzYFymofKpdK2ZAcbvu85Mk3ZSBEvJHgNuxOtu
RNqWrBwXSkbdkJZkdhaxVbcVrK7RHcfGrZVaH_Xlni-eMIqp0jr20MF6a69AT_yYIlndgD_ds37koPx6FruSrZL9npNkMoM0ZLEL8ct_721SAsh13EhY3V7F
zvYUCzU8agVNelwNFHFnzlx02elGwpbsTKMl1UvRmsxFQ66owZj-hJs6uXFn5u8ehPRgh_Ifm7sBzO-VhQlbul5Q_BPj9hWtp1RDoxModIrmtzAgkMEsfXJH
8rMbiN4WPiTuTQf9AAj9ROgTQ_QEwRAM9_t4U3JlE9Z-jH5BWICMGKiTyyKf_hySP9_-UFD87N34CWfaienPwnWmJsgI7nZAz3jIZJAevDlkzKR3VE5wng7J
sNNxn6VRFFvA2q3QJTZS_ID3UffH738CMvj_Ou7FVfgjWH-JLjePFy3pvjJYER1U_-7k2Q9uxiDpO2dRFkuJGcZk0t2Wd9snRVdnYkO-F0UM7nKpXTpDVVqS
EBi9fagJ8jAhupamnpyhYkZclduEv6DLwUb17Tm7oB6yFGCgIbyYm7DVnXYU0zdSZfr-sV3yextxi68GXW4eA8jczbyu4_YLj3DF_WCarAF33-o31eu3zW43
nm7xW87ZW7t0m570Fc3WA6CVE1z8x7kgWGa-W3kHWQs3WG460lk0WSe-Qg2tZnhexQC6UlkeWTu-Oo2t3_z_cyK-Qg2tpncuVPQox_DvuEjq_yD7zpzz6T-h
tpH_07RR_05u3Vl6RVUZeXzTzZLv_jctnIzwddqr3RpYHsq5x0C60lk0WT2-IZl2H_oqLi0-OA2mpnlexVC6UlkyWTu-Rw2tpnle3_czWTu-Rw2tpnlexVC6
Ull6PGtxnkrJsbVJm0nHdyw-cWPUWSgvx2jgO0lNEODzikxjit7xS8dju-tMFjzPr3vlu1vpP2zp-zBQvzliwFlIZhwlTRFRLtCTk5fCM9xtF-fxp5lBtzPQ
VDvgjLgjLYy
}

!define KubeControlPlane(alias) KubeControlPlane(alias,"")
!define KubeControlPlane(alias, label)  KubernetesEntity(alias, "\nlabel", $control,  KubeControlPlane)
