!include ../style.iuml

sprite $etcd [256x248/16z] {
xDg7OG8m34HHMrtx3vpUUn35dFmsE2N0fuopsxPjsxPvPpJ5dez26zv0ywsWlkiV1OysBB_KumBJybk2lzxpHzfsFVu5AF9FRFPT_yZXBi2FwvjUWFF_d0O8
oSC4DLiF68MQHGmGkZK24Ber0f1wDTfu_IC5IBqQcm2fL-8JO3tq1JXFBGWWzKg20TR3NK3ph1WWzMgayVf70f1wDGgGUZKs-wv_P1CnzTQFGivrE2s-7YoB
9TSJl4BguLz0Ss4Ca7er0f1wDTfu_IC5IBqQcrtNrozG3rsiB9wHLye0Mgya9a3kbCpwNx_p0IYlNOoAF34NNpc6D4_fyNV_KzTz19nqlOndjynTQwBqAWYx
l8JP_uRlh-zTEMD3JcS1Omr2JBHbl3up0OoO-3-TAZy2j_7JQdFfTsfC_R3qNzSJqlom0f3lDYQwo5lWy-KV6_JK203bpq3V9rryp0x8GVz01FmJoZ-Uqrtv
kFQlqoNmUfm0WeWUZm2V0EhfQnchHwz52EYVYi32ov-FdYaAaPCVFdf-1D3onrdlZ8845OMu1Hf5Rtcs15aEHG2tG3A9lZOSt0M_Ol3YkG3pWwC_NWAxM3M9
RoM01Q2_fA-wyV0o80AO0XhY_BZ5GRjBF8bliq0ZwBLw5sBhbIxzrXkDEUHP89tG-T5kGhP-NWAqMs_AH0GOvgVVP2IRDT2exP5WV2NVWqy01M-nrXIXPPCx
ylNO4cmB19zg-duHlDhpeNp7m4XHBP2YqLrR6UBLHN7xIq7j2TFyrBj7f-dLZnJnvgiCIiMVMEtdDxpXN4mBX8sTf9TP884QHFFJmAS5m8aMo11njOYlCo46
bMT-_BlUcKY408HT_dpyIu0ySnf-G9e0AiDf5aZ1WOFwFYkV009DB6VMFfy02YX_LW0MVaHbjF870W0KhvCia4pmoY9A7u850E8QG16bBK2ya_3dI5dPkzkv
rzqG9yS23T5gldrOQ7LluO9YWMJ6LzZ9NApkJ5mf5iX6MDKE0Ndr4eD50BZvEOU_v3YRVOG0X65-JZEpxCu7bZv10FvDwaVgdWhnmst621P8yI6bxhuI8dcG
Q1mB5FYUae04ZLu3yYrGmUfdGHkmLfTgV0i4HzI17Xrz3IoO01PV_IZ-FUvg-9jD08u6j0PkuEDj3gnf_0dkgAiF56X12oK09PU_3xs0vc-6qOSja83vD02_
1wPS2sIW-Xb8_Zu0nhL02qod1lvC08nhWL0zyMMIeBk0SIqG6islIivMlMhPvQTlzQhqhvBHg1P8KJRfPRlKJWfANXcaRF1J221GzTDEMBSyBdMPeK9GG39e
VlmCVstTN5v0RF3JB12ifgg9KMnpnpSbgito0HPeMFtq-6CNt7sTQuDDc1R8OJ6L-tZhFX5tAMD78SVn9-5EDd-2sHQ6x58ccf0pB12W9PePd-FlembQ86_A
dt7nlyj_RVA_hoQM1JAyago9KhtBVxBFns3U0YrSIagpuSOMYLsFAqtoCYmGSfRGBTcv_kcJ2RH0HZ1_pMwKbofNjp-p3fWGRu5qO2EnwkfDSdiMl2wSKJRv
Jr10ZWwZKL_LcqPMngN_ZQnSzlLXYh5kWUfU6ecRcNiaSEjwbe-rtCtC5R10S_IdWEF0hY9yz11ORaPH7ki_PAClmjdTAg8q83iQTmH_tXsae4i7G8tAw8jm
jtVH1Lqw06eKE0J6otyTF5qfwP-01SBBtmz-6PJqNu05mbMqdcGEfVkSpoWWF8I0vK3E8XImG3Z-8wPAHlUnKGkam0XEQC1pDWDS0Jb0eJhVWSlFDh64so4K
qk-WdkY_8CW7PuhtEx6ZvyTqzw62FZQAWNPFSaG_ChpyWVLg6MZtL6Vp7Vx-Mh7lJHknZKfWF07g9FWvqH4ExAgaenr8_EJHCT8I4-shbwSXHs-XqGyjOmH_
oK75rc3tWTKctdasmj-brjWN-7gGU58Fut_5PHxMkfnOBPC-zMrpZ1nvEVi4vutZVza_2L0kJK5KXkb55DHYLJTR-msimeq6VAndY_wP0Abl5KJbMX7X4H4h
wwszK-BdyiCVcUjOkykItm2NDIFYoIhhjt3eP4DC_Djy-ujLajA_sty-HMgodq3YovClwtXyg5QbNeB7LpUY0-50LK1J7-W60qO7NgCwrlR2xDxkumtn2ued
hmd8ck_E7kFBbSYLslbQISrE5j-nWjL3tyS3MvH_lB234T6rMgH_myZnOPEH_Jv5ftmE59JxUTmtFjqrlmSiFlVr78XJLHG0dyzzV0xyJ--5ODb_HEuZSU2k
hlnisXK6d8rYHv15IY_rzTRG6RO98u7x21pOZcrT46erq0dSnuYn0rVRnYtEchn_040SL2UJ-_WSs1DC_qi-z_4v4CVFvpu-1-Bvp-S-FWVY-FdSn-V0FhVi
EUuZd0UUMupWSzy7SA3VgL5zu0zm6HpOrt73VOJ9FCI17M-GkUzv3km7NNJkUvu3i_qDc_kUvy3E_wKIkUzpE50zidw7lS9DvG7kUr87YgYQgJpbUP_tmdmE
UZtyVFc_FVkm0XY4WHXwXb2y_y8PWgfd_WIfecd4-lQjR-28zUrRty0yPhnzuv8pTKtoEPAcgGwKD4ztd4ypEKtLLCPktxZiA9gkE8XflkOOMIlmsXUpWKsB
P5RxWZRGj4v3jY_IHBXeAQEqBsW3jLn1j2zc0xDsw83shMI0zWLiODSs1T2-Q0tCsga3shUI0TgtL0AqRwaFqBue3KmweGFQ5w61JOSaVll4Rw3fd0fl7x-1
HMS1shTK0hUFtq3JUHNQFdu3Fzs1UCpDRs3NDNBisvTIxDkNh7EcVVn_e9akbAhlq3_Toz9QPXhtFC_pF3y
}

!define ETCD(alias) ETCD(alias,"")
!define ETCD(alias, label)  KubernetesEntity(alias, "\nlabel", $etcd,  ETCD)
