!include ../style.iuml

sprite $node [256x248/16z] {
xDR5WKKn34FHIM9I_mKFCxFUbtCwaBsvP_zksxPjsyQbhjjNuaPvmniu7glPUFsrMdtM1rxLum8Zy2RJNvzubxTTht-1MVYK68tNNqkv2wp2jPuNMFYwb4aY
m_VKRBPUC0eTFxJ4GlVhJ31qzIym4h_8XTRhNs0M_a0ClTGZH25nlVu55ZvDC0eD_w6Mm7gv2pZ-rH9DlSypWVKA5nW96XT8FK8K4jPpBy1FFRqeN3YEd9tM
yxFOS3or2AdNy0AE0rlarECpSkhnENazdvDJZoy6Upt_0hpGrShYKJXHmMqzlXhStE4RXEyB7M3Yr5qmTwM9ZVCwhDoP-r_uJPw_p5Xb75kDm6QMFrq5Ie08
KwRoBVnmZLPuKcKVI_xjt3_Pvp80Ybx_YKn-vW8GuC8Vd2es0Z_63-EcSsUEoJ_5ZqHV_t1y606esvYmOvJcW-Xl5Jq-0Xz3VwFpHMSVimE2qFT7G07q1wWG
R3iCIEu_d-m08W0K00EW1qG09W3PL9OX_6CtMI1_6FHYUKiJS0IyWVxpw6bdVbq9cHJ-X7zOtejbiSCCYm2M_lDpRpFVml4R5WYh-IHUliC5bXRRD7n2ehUu
qvrt50ZZ_mi2OmhFEOrVaFkzFUXEujl4FwB1eBHu6hyZZs7OViNJVUBz0b796pCW3FegVy53fiSWQwGz-5EcKslzYWcX9kknG0pW_KNyc0WWp4_TP23uwxVZ
1I1nwC_n8zQ0OEdlz8N4NoEGK0l4WEXEu4VO4wJvoQzs_0p57m3kJ-17A1G3wS-_WD-1-apWx5eFyHE0elCS5VJpPOw2VtON8Q00EBw-85dmEq5J50BJVve4
EU1F0JjKXU5_wtZDXZzrFdum2yGm-XT7l-6V4cUy01YE_bK8zIlcY8yNWEoWVtzt8O7I__CR3ZY6M855sMy159POYkSjb0u1MTxIhjC9X3y0j1ggVMdoiY3Y
GXS72X4gWAmErRvQy6Jx3YMCrpy7CmJzyySlZWKN67DFKnbYWMIXgjRvhHpObJ_g-i0B0DxykCd8xqq3sMAJMvUn6BXf8AdpQW6W9lDJH-dwm9WkVmLXm_-l
_EdRLpuM3AyM00NWlopJeNUCjDy9Dlpxum_t_-9NGoiBB13U_CJmneFbjzZfS39QeYojNWja2_UKob8UXbpIBHk_-3SiK2xFVaP82_13BT1iH97u0HO8bltW
yUC5O3wYZiM_N01MUmh5ubyk00p8Ve3ubmk00Ie_IFn02uIl_CpZruA_sG8vm54Vui_POY3U0a4UgKe-nM_JnK2y1G8zKhUAt-cW65XQkZLQ84RLbCaU0Ilm
9eg1S04mtA4YZWt_4JpRuTVVgW8bilB5kU5FNL0C15WWVE5RyWz-MriCb8KMY1egN_JwazHJ1ku_ziQgc49fhiCVEFcB1Uq9uHO8TwA4Iy3WPU3vKHDE_cH1
Cnwu1HAS_1cmF-So0NI0-Hj5Akbu4o2H6O44M23SYL8RcY18t9AVqZYvuKLrQPG_hgyhvFDPc5XJ80l4o-MF_c0DZokR9nLnQi-0TBdy-L3lPjOub66Um0-o
GBbQ_gXoHRAenmH-W0L2oXy_-OsKVvU_k55PV1qPa2sXaLnVc5f-JMoodJHywI0gbawT1-5a_RClYYUBsZQODYG4LbWLGtWQCg207QRHkiw-QASCGz4_g4Ik
vo0SvZXvrb-NTrmxjcLfYgbUSWpuGs12dARTXaPrjhxFcSizI5GEYbcR1HAC-PMAFpVnp7hIhxxbtoS0XZ6_KdUA_tIFiinngOSmE0F27oQsGXLvNDYYXnYz
m0TP83p-BE6ElsF8OOkhUBJH0Z56_gDyiVqJeJYUOYyg1SY0yAzJHecMxYAOmnINTHF0LfNqTiC3cvgMrDBAIUWLH9d1x-ytX88qbQE1CHuv4CZ6OTGf1VYV
ezaZJ4iDFsWLGQfbXklQKM2lbWNjdlAQ_8SoMtvRDiHseHP9kFivoaI1sWeAZ--0s7wpffEraqgeDhtyBlr_MAUdtLBB2wpE3ADPYish5xwldZxMdKsVHGb0
cqPRWZzfyYbjxYVChyeQhU_IwKlmtsAI0BOMFoK0FwW8HEwkmrOJy_YhzW7MFxYthkKL_RkYaxwi9tWqNwz0cjVFeicizisFMlgl5uW2hEg52JD3EXHFvF-W
5-3fjG3osUv2kNBCqN_1XhzC0FsCMR6q8J3rNxighnO0bq_M-2pbhBStcESo3nFgeBVLuqryV-4A8UbO_FaaTei9IzqTvlCuSdh2Aah0VHZIss7RZYs4dkqh
0Mc6RPqQQ8SzWydFxBM3RiE8FWtKm-lxzJIc2hWCeri3dzzzG68bfa3jwzV0YjyV9T_C6dt7QHz00tMU_axVIxuXH985Fq3xsZMmmh3gzGQ5epRjwzT0kwKS
dvJoWtWgu1wGVWsimIYsr3AuK_lwDR1EQrKdlFOjZh6-XT-HvCo9mVHxuOeVg7spOSPxuKfGcFPzf0R6UUpuV-tPns458H04qHay-IUiOvzb-BMhfY9O-t07
xUCDhAst1EtZ3MJjumraxUFt0rdxU0FFsTVY9ttOm7FsZL2SWRnzh86yVQY1l7seWRnzg86yVQY1l7sCWRXzeK03UVjG0tdxE0Fhx-BiKsM_iuNEF_ZG-ITV
YRzhRJH-0RRP-0MuftsgUjgd-dvHIUu_yzKuqJ-mpyB06ShHm3XMzxHFpLVQvpGHxd6qzBHFLK_xLFUqJqrF-zIoj4_bq-tpD735n-gUzgdfQPzQblQfzBHF
5K_xL7kaVPu6bY1QblQfzBHF5K_xLFEqJmrF-zJoj4zvsgUAftsgUTgdXgbzl84jdX5xpCrNFErJrVFsLV6yVPMBcVPv_WCpuu6LiJ_HQl7SifmjCtxVxNQx
tMvV
}

!define KubeNode(alias) KubeNode(alias,"")
!define KubeNode(alias, label)  KubernetesEntity(alias, "\nlabel", $node,  KubeNode)
