!include ../style.iuml

sprite $api [256x248/16z] {
xDRPOOD038JXh6xrNt0kFUPKOXiOxTV1o0R-fuVRjctRjlLgwdRsBA43Rw1PIj3SzILupdhBJysumBByak2lz_oMZbsFVm6A_1LRSzSNXxi0r_gX5-3iSvWa
aloRe67h0QDGyvyOB7Jx12nq-mGizVfqyFgYOAdNPmilzV2YiDPFlG1d0rmKIZv2CC1wk0jeFXI3fLwV35vV12pr-XGizVfiJLvV5q1ClVD78UTvE9ryFLWM
IpR0HQ7cEGKFNbyOBFNw12pr-dJm-gANIJqNFoeAZryVkkxtIh5ryj1zOUvA5votGM2v-Tx_WNkttZWu8VQWUF_j9Gl438EieDoOIlFEifXoOd9RffhpWDzL
wmKlYZ62oPtvQeKdg91kj_hEnomRTtC0BwPbTZW4BjcF5YRlLuFiHcB81gt7Um2FW2-j0zaz0a2GOgVxXHS4f-sF2UlNUu17mdz-MqRpkm2WrMi_90hpU_1F
1Nn8x5i442kj1uX2T0OSidwz1nGEVxprax8uaDeVR_sy1r3Y5syzJ1JY2I2dh5_l0G7I7zxwUGyu4lvuw-SzWDpvmIlDUGyWuO-tVju3F0__bKqCoCQNXkvz
2ebok0IILU_TMMN1nlJiHxVoWhOlz2dXqnEDmjyklbw8tSzIqFoie_RprVtbvDqf0mT_jZ16rGzWWyc5_dgijIJRF04Ophdz79EVO8f62I27mDL_Ic89G9R0
7nXbYIK0lmtyQv4HRjwD_ta2q1durnZUtecJPX-mD6X_BAfxdiykUt_Gd0FfpCZr4aOPUepkBc1ZnS-rK_HPaoAy1CYfuYUkdI_W6dpu4W1H_E3XxmTsuRSe
Q0Z-0bp-BG08_e9EX-odAyLV7lr2uMyeOaRzv2NnvqVFZoa2GFlLBxtQjyFq8sC4C5_yzA5xR7yIcW3aFkh7Vxsr_rSoc03yFkedNvAIT4DBC0ImllY9btEo
eJsG-nG_Ne2ouXzm2NGRzQD5_5JnHryeWMXA_TJFq1U_os-KGB92_VXn14M3iIS9m84vnJ9SwgTaxG2AZm2R-6055XNs9f6JvkxbgMJXN1W1w5hrGmsGsC-t
7vh5fvU0113ZMxzKBWvzGZUf_DT0mWEdT8RV_DXZBFSUArS41Ru4olCPDHxGBbstHqDFu4iWlFhn7xlvfD5EajnWA7W9X5S_SbeaFE19L0OFwMC9DPihSUHh
px_X4Z_YoNS94Qo0i7ZovaheAtNmqtF_3y93v_GOgtwQhajwWLpTFEV_Zn7WlVgPYfeF_pUDYLWiT-PKdjuyHrmW2qe02HtjY8jJDZx98msSFzQ4pTsDjyNq
UGB07tlZ_oTV53HXVtrnnPVyx7tvaWAwbarhZ4KD6Txyo4t5D5y2NHjhX_MAegFySQYgPUNPjIKGNqecT11XKWUWDZoBBu60Qh9S2NiZAgGpSHqiWM1Y8aep
-Ks8QiT-6oo1OAwqqiftEKewkJQ_KmBH5VgJ5_nI1aqqnbvR0kbv-kDuvTxSX57ri7HL4VKimuINAQ0uEv3aw_polmYaOjMCDbDiXoxnOion4kXi9kK2kPKm
uFmhrTC3Q8sEqBoT23Me0W85ajKCT9YYy_-5IezD-hLwpH7oBH28IAIsNuuOMejv1lKQBIfI0O7YYEe5Y2E0qZEzP9U77Ag0CCCS0KVgvSzYVEf-kYsW2WX5
V_K4aihmZ6TwaNP42_GW70H6ViXPIHMVvLEUyYwbfovHG7ebZJ0JSRNP8rkmKxJt8gcm7ay0U1dXkoP_70_BBL67OV-466Bg0dLYFUzqK_DyyjZc46s5j0wK
G3Ofe_ETyB3QWVLiOgG40emH9yIOF2IBLaZBkZsWmAX8UakPTQ5SJuT6MbKneE61jRWut7FlCchPxn_ORu26K8HgAlFKv5XovtMq_Ohe22UWhaBqh6yeDdzz
QB_CTAevYY401N3rQmsZtLzaY_zyfZytGTeT-Klx-GrQUv9EiDntF2giiLo-IP3KieoxEw66wGZ7iDQYL31NLIfvqwpKWGRTY76EGIngzBvpJr_H6xn97u6w
lSM5laNMZsf7tqt02FZNHlIPclexiGHkKMgmPfTo_aLLz3cTqFVButhTqlcJ2jxcTFZb13XFPjj-RQ97Fr4Q60AORwzQWynxKKtmUrcai7-S0_svqq_oKRVV
LFgDDGuV480vWteToqS9mENnZIa_YATzP92Q0Bbl6xwmVvm3oLoV3KWJ-kkNOj46bVx2sp_FWVqL953DYu__sftWzbSsVIULWdkz6xRzbKpVJC7eNly2lM10
-iZ1583NHoIa_JfyALNW8oelnNz6P36_gKkfUE2o3p_FVy7xyfX6x-FB4KpfsHwRNXmA6-I-shi0jygvyCzA8GzoN-rSMdtVO1HnG-r32lY2JR2uwjjV1KNE
SLyENlVc9zAV5L6OF7SNAKrIYtxS0ogB0BV61F4ajPu3nSDf7-B2AxYlZgy_sZdFXBjL60eUIGQ9_I_ulVJ0JRU4pstpA_dwk0ourcnUzTItZz301ENj8pGm
GNtx20rCufNJVa83axJAzZ4Ro6_V_ix4VRTl_xBkzzm-UWFvxUCtaDy-VWFvxUCtaDy-VWFvxUES3-Itx_uRs0PhHP0QMD--JkjEt5Nx60sq7ANjOpIGZ-8y
CSYm1w7nw7HcV_X4VloXu4NrGPh-oFwAFC7rvq_0QVwqzl4R66RclFRn6yXj7x-1tFRn6rZTFdu3lSrlH5Y9tbftrhnl_mdHQFhJPy0Q01zk-8Jqilu7Yh6w
54ci_dqgRPK_ocbPVr4p_R80Ply6GBv-wgZnbpkx_WpjNvoxp1jJmoVwzs9vXRzXWT_0k1cNOl7twNzIuD-n1QcRshRP_rWMZQVz7PkmKOBStFgthZXB-sCR
hMfYffE_hN-wJFvrxUCtiDdqXydS_vis9FqDEucQsUZits_--4ZvDsn5aiSYye7V-1zPVyTcxFJQFpp69tIZF_BKDp3MIQycjlz4-tWDxAkCREkVuGhYpEOV
wzQmPVnhk0Gvux_-bR9Z_kEu23lXx_FgXsoO_mOM-0rSL-li24aS_r3QbtzNuZ6_x43gZtyDLn8dPdzg9W1C0KcS_qYqZzP0c-Cn-PUT_t9SZ9uRcgIF7_o7
Q_RyPw2O-ej2lfpzdls_dFzkJZZVHpeVkFgdKJ28U_5le21tukyWeNVX7w1nt8E_W4Vd-okO1Dk_WGlPtq561vC0dMCG4V3ft5jy-0Jt5Xy-t5kx-IYtVNoC
gyz7kVfyvE88Dl3WxmCkk4EqZok80_UBw5v4aEVDcpTlthpv7m
}


!define KubeAPIServer(alias) KubeAPIServer(alias,"")
!define KubeAPIServer(alias, label)  KubernetesEntity(alias, "\nlabel", $api,  KubeAPIServer)
