!include ../style.iuml

'Cloud Control Manager

sprite $ccm [256x248/16z] {
xDRLWGCm38FXYo6EzX_uc8ikfdA-3QId_-dcbcLPbgMzghfT0n-65_p0yTkGgkk_3AsplcEh6W-qZfsCVtrWBo-xdly16JXARrNNVmcw1_HhVSa757b1aqI6
qmmfjfum2XrdKhBGpJEoqCqpijJByxBhlpXPwkNrnfLwUT48rbC_e4YWYqB3BGmbM4_tWEEcb2prygpi-Yz6bdfvJfPwURrLNl_rmFofnnU5Ydc4JBwUB8iD
ynawG-hnF-2Oc9AbNfwHfLwUbrt_nHyczSBYNb5u__Klp5tfWlCs22mtt_i_SE_M6mSbn1uSxx-zP86OOP0Lb4PpbE9qSw6R6rDftbaMKqvCRijKSnxmksgz
u8jYZ61oPxvQuGagfDkjllEQPUDk3k2BQPaT3e5JzgE52RrdMxkH6B91w_4Um2FWI-j0Tey04AJOwNxX1S5X-sF2-kizm2FXFxyje_bT0D3LQpya2lDxy4y5
V4ZiMmGGLre_AGe927-yzVCUK3ZyyTPFok90Qd-yzVCUG8bVlFKmKOWdW9oo_deF293-yDRFUy2HyCTRF-y1vCuFNcdEUm09VxprynxWUVXVsSI0R7nfwDwd
a2Y7Io2vwhqxgromCJtxqQqyeUqBVKhuz4IZyBUJhnTYzxCKD3_hgFryTdyvUNVAmC6VBOnHzGFOO7AXlnvhBSasJm26Ssu_n-GdcA9H0iWXSFMVabW2a67u
mqlin1A0tmR-jSW8D-_6_pm1w3pyDmnlxyH9imzO6hG_BgfxdiykUt_Gd0FfpCZr4aOPUepkBc1ZnS-vK_HPaoAy1CYfuYVEdI_W6dpu4W1H_E3Xxmkxy5iK
D0H_0Ix_5W04Vq6dG_RJcU8lLxzG-1kAc54_UKhy-UhvCKK0QB_wgLVxjam_CaO0yyLF7xfh-vFG123tKJ_-wwtzlvB11E3tKJ-v8wLQVYZuXCfzYfzuEISR
sWEvJ_7Z1IWh_W6NGBTHFrh4JnL_z8KIYARKJ_qCVV6x_4O995Ue7rz7K3GOUv8079XJBCEbVahM3g3u2B293rPWKM6l4lcst-LKd_Xqz1w8Ngj-g04I-_ds
GxFuz1AG069ywvVAnQ5Fw2QL_nf8UE2Kpl2R7tkCvTvZvOoWm9T0UJoZnWFQfUlsQEW9V0c4Lp_-OpUVDDf9aXiC1I-1yEf73ek41po9ok0XVIoXPdCbLhxs
_1ikyIEUV9SGmGe8YoTlheI-KWS_FVV_83nqJe-nwgVfkgGNoDNDS_x_607Ugv-fg7dvlsbCn6AvCwVozEOvuW9PK098w6WhBaxP-2HN6ZX_h0cRknjlY-dp
180_ziRRv9yBch2_lhZYItxsldn90PtBfZN6eeOCRtxafcAQBu7EZRN3UaNHKVuuLDMoykor9H2VIYQqY32f0r0RdiMNG40rMQw4lH4Lqfcu3fP0C34HfPdy
9aIrOxyDba0mLrffvRiS9PrSczyfWUWC_SaBVYc39XfZNri2wN7wutZbtjo4KVMmT5KHzIp3X2zJG75q8CdN-UL_4KZ5gXbjfjWENUBRcFCbqD5CoWLoAs70
-LUgfmVG6gtGl9q8DQW20WMIrGoqJD7v_qAbnoRzMhtc2FaM24GaKjilAuRMOfv1lKQBYbH0e3YYUW5Y1L1wffViyf135H1cc1Lmf5x-BCQdxgVR0gg0KFHN
Jo2f3CzufXTfHxH03y91OEHBpagg-2oVyfHtAJtr4WMaPz88Cn5Ncpso1Jj5Uo-I2kln182N4RvhyiURoRvhPnE7JeWXfYvG9zRpJZSrpoUFRGxHLaZhG0ba
ap8wtmaFgnrOpoP6IY306750ZCb3icY5j5ot1nGO5KblARCkbElfq4YhAWOqFB0M5uTxxbr6BVlz0_iDq12AK4rbdfeSI-wyZhPV4HtX1DHLY9xr3SNchm_j
bvbEDQiO0b00Lx_MCDhzHRRupsVwSnEatP6_j9_VeBKdwGJBVUjHOOtbyas2f9PbtDq9DKn7E8Qr5gM2kQfIoPjcfGuqw4QCimQngD7xpZrzHM_m9dq4wlOM
9_eMMJ-g7Nqt0IFWNnlHPshgxyGIk4MfmPfTol4NLT7dT4BVBu_hTKl7JofuczFXbnFWF9bj-xM97lr4QM08OBwzQWqoxqKrmUzbaSB-SGxqvqu_oQjklwdq
6sii7n20EODw7Sj72S3byOqfFuYdVMIGcW2vRnk-i7-S0ybSdmr84_hhbsBH1fN-mji_pu7z5IHGpOkF_zgTuFPNDdqdbO9xlHks_PLCtqp1w5x_0hrWGFh8
mHI0vqSafFqwV2bLu2CgJyL_HcGnlwbBgNZWiWy_pd_1-_AOHk_Zon5CwT4UcruS2Xlaljgx0BVAiV3FIY4FSb_jNBhwli4eueRQXnJm1PjWSTMtlmgAdEE-
7BpkpG-aFokYC7dkBbAQf1Rzk0TK5W5ku0dM9FLz3XGFfts82uzot_ILNz1E-FFSX-V0Fzex3oL9OHY8jcmBY___uCkQ6b-24oStM-PLsj2xCprb7XaZWGJt
4HmO8CjzB0V6wGcR_GG7Hj5Kz_4To7UVKpWEvBlFQGG74jp7So3VVNm7yjt7To3VVNm7yjt7To3VVOJZWHJtCHp8Trz318u34zotqRnZjt8Vmu7r6idkotSW
du8ujfDXhuJsZyx6z0yVewv_-E0oswhkSsnLzpchkiyfgxhFQQkwpzbMTPzZwxalxi0-FFeWcl5dADZkVFskimx0dovVXyaDGXa5q5_FIYlsVXUWTCu9c1eO
TIsIyVxZW_9C_ar6bFEFxXmfjOXt2sGKW090-HQ1x2R-tJaP2UVyStkxtTzKMZ2ZRxU2T06W5T3NTpLst37VWHtZyBH8nllBU1zrVrkkMHTWd1dz-XyoEWot
CYnzxNWaTYHHZvqhUpWpzY_3T-D39JJYldm7gkiic1b3G-CwV80juhvy1rOF36mlx4p6-s_3SDRp_IioiODNjh-CHZsJkTfVaOeSg6q_wEQPm_uzrhyZcNhl
_d083Yp3s0vchlKNvDFF-I-UYVUlc87bhl_Y_HLJaDJjdtZ_ZadKnEtVU7_3D3Hl_oVUN-3G7DZUP_nHQO5Ck7_5J2pd-4Uyls8gadByAzw_Op8buVXdlByX
GDP9eQwgVcmxa8aWc4-_uQaUXWFvA2Z8VWywI9HxdUQcE92FWCUsgliSuxkF2zrzP0hPVNGQrtryjaNTntTWmptWNjx8ft3TnwTow_CftFfyn3YRVMik0rrm
Gygspy0QxekKN4HmdOU7XuU7Xyy
}

!define CloudControlManager(alias) CloudControlManager(alias,"")
!define CloudControlManager(alias, label)  KubernetesEntity(alias, "\nlabel", $ccm,  CloudControlManager)
