!include ../style.iuml

' Controller Manager
'
sprite $cm [256x248/16z] {
xDRL0KCn34FHnX37-mzSPdOnJyxPGFgwivyRXc4OXhAKTJkRRpHD-87wiKOvrnyqphE--bKv7YZLRnByzUPtQThr-0zGywVKadFzWS4zm8Vr2HzWZpEO919_
JQDawm6ZKFrD31QwSG8Mkd42bdfncdJzWOAbNbmjMAaNPmLWFVG3x05mKIZ-2uq1riCzeFvJ39PwSP9q_O60fLwSWgLUN2rvrnyUw3_ryAAGlHz6dQy7osBn
_ZJk8VNm7r3l68EbNfo0fLwS9br_e9D9FHERH1GkcBlIHNTz5NZPEU__mFU_rrEBbUfWFPz-Qmo46OOOoOZrQJH7AKut5xgvC9NcdMKnvSJabamrvm6_gzOB
lYZ622PtvgiLdg12kjtgEs-pRDpD0NmnBRF38N3AVhGmeNssjHk98Hkq7ky1F0A-j0vazmW0GOgTxWzU41osFoQilzu3F1B-yziocjy505szzaEYCBy7_rJ0
HsBV8e2uqdg0A4Hdm27hh_U0mk6FjtvI5WTI--Ejd_S0IlpYhOU9GZm1v9Jrrtj0WFI7jtxU0uw4FzxwUGyWTtxmIdFU0qZuuwsVzm3Fm__A9WPauqj3zpw5
H3bS0ibLxzrPvOADwTbFj_A4jY_qAU7J4ut2tqw-NeZLdwMW-Lb7xUUp-yl9grC63lwsC4RL3s23oON-UgmzVlzT0Z2SS_iv9Z_158qIG0w1g_-Kn1A0N09_
O9GbbW3yDl2lHKQuUJV-vmb0P-1VOtXv9qwQVS3IeFrnKTtpUdRP-uFc74XdHgwNCChGOtHt0HihViwTei-Q5E4bG4uLFt7kV07NuCEN08ZY1mz_tx0BlqL1
G_0NuF8l0K3m5tGwP3-TAVvowoyK_eOYPjHFdX9_llNyc280j5_zrAjzsqm_CaO0yyLF7xhRzYUX2K3ketxyPzV-dsGm0VXzr4--9INfXfPW2E3wuYVUpic6
za3kK_nu0SgAVy0bq6tKZnRnKyKVVQ44eYdrKpz3t_nTVgC4aYlKZsz7K3GOUv8079XJBCEbVahM3g3u2B293rPWKM4xYPmqLozF9GldmWX0hrK_r029_Nxx
eLbylGGaW1ZV-gLoSUWJkadblmOI7ZYbC_pcnvvZkVTOEICey2LG7i-eyOHswRez6de2NmBXrO__siqdZNQIv0P3mKiWlFgHmoBX2K-YCdX87qkesLo9BLzx
_WsN-1LFlag8O0M4nPCtLqBVgOFVddiCmaFdz1YhVfgkItg3N5qyvuyn0hnNFrDHy-R_JMCY5ikLEPMd5yyH5yY24a12HzlYufI5Jt9B0-UlDM5pT-DbCNsU
0F37tlWn-QAW2VlhXok-v5VlovSKqBbiMcCiQiZmuaTkAgRv4kZSM2kiLnGTvH-7gbfMdhss1E9JoOGs8apg0DI6P_4b451DbYjXEw92EXFNmH889YQYD9Dt
GbGxzjjW2GHpfPLMxkKewUJQ_4u9H6VeJzxmInaqqHZxsX98ZzCVnpltvYACgeUbgugePnacV9a2YgC3IRxFBmyHICMg6Iscs0fTuiMOOoNGqKpA1N8hOS3v
Lwgd9z0QRQ5vEH5gK0K42YIh6MWpHUTZeT9ZaNwjNdE4V0i48XAfxPSjXjPYda6zHekAL42WEA9w0M8BeFHABzdb8OSg8CmmMy2HUlcp69-wNxS5L06XwA-U
G58Pdl5ABzAEQ84UX8F0o3SvAwdYitp9KzwbzDHB592UIIFCH5njziWIx1JjlKWghCSJ05v6-Ah97oyc-wgTJHmw8OQOka2TMCyxtTGyNposE4HR8Qq39P1D
okZS4nvMEx2UJOoKG80nue0OawTaqGffkMuFA30gadOfiowKw-dGIAig1ZGyi1ONXtkkNKOj-_q3-mtG48fGJMLUcXnBhhoEjbyH7U44r5M8NlKDnUAl3-sN
cKurMp44e02k_bh3QFKliiL_FjEVco3jZloj_Ro3rfwa4optROyAQooNEmcIMfPnToVKC1tX6DPQb0hcgaebRvgLEj2W6p7EDeX5ZVOxz_GLlS6Rz16esrkS
w5ja_QXszDq4Z81_RKIVgQc_4qlW5gK6QtOfnrzKHP_J2Ns_FAxNBHq_gU1jJeTVJe3pPBRjroPwz1EbWI60-VQgDSYy5zK4lvT52ll7ET1VE_qaRtNxJQN_
iSRc0m8mPr2lO_ae0RWylp7b9_6qZWnI4o3tBSCNzezp89dhgm5fyjS091PjKEaFtlvv3kol885gNdpyr-u4jx-owJkf5DphtR3jhsJwPWf6z_eNw0K3qaSE
fW0yFo8XxTVXIwa27r5vAlup8elvJLrAnGENVVXn_WjUbySqUXzVZc1AZ_ROzE9Gs23trTu5k5MEXNzM2dcG-shdqjNt3KOHDzG-f80ls0IBgxxzLL3a7FVb
u7LlVY3zMH65oNDtaT8ajUZ7FQ2o271hJ11FKjTpe7WuhKDS-1Bkmt0W_ihHFzex3nrPOHYAsWcEpVz_yEilOWehThZanX97RVlEXUIaQKndWFke3jo7u3w2
0_SXk0_jG3oEd_Rp7NWSGxgFua2--uPv9dAv3t-jMmBtyHp8Tn_VWNptyHt8Tn_VWNptyHt8TnzXFv3YldmEj9Lr8qWEnBklqRmJKxcFuS1w3gZx60xaK-Hp
OYN37eJMx3IcV_W4TVpX8wTfkTrtdiZiFWJvtKTmO7htvNUWm6WvtOSZChkFxq1_A8QmGpJRre3y_PdFim5_8dpTFEvWPsFMUsMq4jlt_AcJtTUfa7QuxEL_
B8iNUbOz0iVEM4XBBVf5VljNGkPlKmljdtse7ftb_7dP5008qxty8jfwFJ2h8jO_gwop5uG3_Qa9nrv-VNpNj6zwCS1zD0UM0nt7Uk3UNspRV1nmr4DoO1ov
QlOmnRQN4X86S1_9WTQLT-I7UkBwS04NWFj83gnlVwLrud_-zj1uxJ4_mNt0GblnHViqV7uJ0CZd8wn7yZiglyl5rBdpomDi1vO3FGQQN-Lw_8J_BivVPGI1
6V_m-Ks6e93v3pw_oo0gOFwBpnyo30EiV-3vLSRXtrh_BZlhNsZ-AYC9mFu7DB_9K1Im_uNCxpAO0jZ_nEKF0O8_57BxHOlrCbJ6umcEUWWE9612GTSvS25H
vZhcfZYGZmgFbjnz-HremeNkFZ8biVloEr25JqlgllmEN8G8tu5D9g5mtSUdSkFpATpuV3JoJFlozm5NcP3IrX748lEYvLfKvJmtDpStDpS_0G
}

!define ControllerManager(alias) ControllerManager(alias,"")
!define ControllerManager(alias, label)  KubernetesEntity(alias, "\nlabel", $cm,  ControllerManager)
