!include ../style.iuml

sprite $kproxy [256x248/16z] {
xDO7RW0W28LXPNF_0tUHPdMtr8ZudS276VzOxhgkwxhcaz4KgWVZXZTW3y6Wx_fWEDeGVrUF2qpn3z7vwzK_nGtMTxq0c7-BpBxhWnvt0OprJI-0_dCAun3a
lsFGRFs1KSZ-HrWxT1DGwT3jUe6fdeWRhmzSBFNooJmlzSwBmbZVzGBe2Sf68VaAXWNMjxi0-r9OBFNoKUFrWOgbNZukbdhvP7PU7nUec7hren1z7mgLrjVF
OlBz61PCFINDl42jzSOpkvwmJkePZLTadePgf9xY2FaNu0BhuLzZWXUaNkRw09ePXTkkbrXVwG9egvu5ibyMpxprFCTN9diQ6GaeUVtA2zZS9tTuXBKNc7ly
lj7ublmWU6JkoXRSXa7WShF__y6zKYTHS28dPknzQlVsO6O4Ge9z1c0mUhm5SXT-E7gy1Qo1_3ZqOlcTnWqBBu81MFIaVbkgbDOj42SwW03HisL9XnaJ57wC
Fs3R4JRvaLOByAVuWRmdyV8JBWrXSIC128PUNMcaG1Z_5OHWW0MoWVwzAvxT4F_5vNAr1YE2mWRwDw2lz4_xw_6B6QPS9Jzs1SH5EpPi1sXirIgo0_S42O6-
ohyEViQ8r2XWiNzLsWRy_HO01RyLFGf_jG1U0B9XTmE0loWXgYo2s6wSuuTioZc0_iN0FVWnx0Jl_EHN6twCEeFfRttuCVB4MFhp2VWTcm8HqhtqANvgu6TB
2YJG-8gZu7zt5I6i03WulfOi-8DnyGcTJ_-wlJlWJq5UhbCa_XtRoml-L6nf9e3HJ-mvJdF1R_3yj27vGLGOEFGhYkoTBm29edzzZLzqnErQWTB_vr-uSHpz
0T3EJW4KGt-n72jTjIOKjfrEEFpHpopIU5Nf8l5I29a_9KgbkfLLIhLlS0Es1oZRtC1GAH2rfXRahyy1sgTxoOnAWQHHMElxNMeVjH1U_GCl0FZanuqVCCQb
_1SNhVr7T_4SA-6apgq2G6SbFp6K-DBbMlw_u5yCGXhZVxbL01I3VwDCBy3ujX8i-EyN1Rvt1MwjqCPPqKyCDnui7sodGp5GIZ4GbWBXav_AKXuUkSHQDdup
9WLg_Qs2nOzFWV3HpmYf0JyW1G94Fo3yU07G1fisuUyL043oerZylGB0WEW7YxzN00nG-G7Z1wH0oCeF7Zy-1V8cZvhZpu9Vf_ZnAL1_IA6vYjyQYe6050WH
Kbh5xzHG30IaG0pPKo5V3BOEJqVyAQTLWGoqgSwnu5-5HtQ7tqwi0YMigYfvmP_QK0m4f43umhVa7_pMK0p4fK24hdnHGp4G803mOs-iYkdHqei_GF8NEoh5
HwP0e1rLRhcGZK-122H_qd0PzOWKI43oPu3-D0W1S93ynVn2Feam_fuIzTdIF-6eqh_BRCbhtr8_ZKs1yFB7zGbp_KLio53mAH3toX_zmHhkMxo72gVEY82i
L_vyg7UpQ3nL3zw07vy2PMyoNTTToU4p3VXRKw3UtLHU-QEKL_SNjwgGfnw4e-PSCbUKaXRdiM4zZ28gcau77uJJvhq4YXMdjWjC6m82Awpo4YxW8w30R2Ph
TRARg-b3bukWOhd33iArBAIL0bm-bVTKgqVZr2Sn1YO2eXOTgOz6zMqzlZCNfhyXiCKd9IlfIO44aFnAnPyNySnwqgzsUW0B0BwOAdMb-AzxLDvnRJR8XqP0
Y3lLLgWYIyDYVRgEElGsh1nvd3ABhUBw63aiSHMF7fi2CK3-etoptdHeFEDOFG1z5G1_epAAjVJEWldY5UTRkN1qK3VRkZtKrv9IMZa9lO8ex-2tbdO8_Rsc
QM2CHmu4ifS25zlzNriQTH2WguO_QHN1gkKDLzzHLAEMddPFiKt-Gvaj7zs6RIRmMzTOoXxy0UalApmspxPxjjB4TrAfI_lciHkuiL8ka6LOGsQipWYZYVQr
F3U1M-lfudhszbviD6dVIyCBkBKSBJ_WXJzJMQFk1hLjlKxZJG9uBtxAjevmyEQAvE4wE5hinXzzSpA-3nkvORc5FKKdE-ShnuH8wEPYn9hRQp7ItvoxyNVb
v-qbPQON9ioCQCvDi-G7Vm6U7WImeak2pINW2VqX6bZPIo-_ohZkn3Q9VY0QM0NENxr-HywMNnLRj0PM_l947M232NgjcP-MBPEUYp-tvRnp0JXZr4WEubdT
KP0pMMI27w-1zln8bCxMbUXzteeVhu5MchuNCYf4-wh3Llnu3TJQ2AD-HG3Q1yEVEmujXj9genG2Q1_0_wj9j-DtNyv6PcvI5Kh0dC00_CujzFSo0ZA4IBAO
jFbHlxakE70Dh32ivde3I9veNry2Y9-sL86ar9DI0qo13QGAZ5Vbtab3Tv_9O8ZshJiMdJjoJijhWSxYInYlT1T-due6ZgTvvWXUsOJVaRFuwCoPWrmU33YA
CQ0ppNF79GwQs0ZxW7Qc1egQ4bhx9aQEdpo3-dTxPuBSi0e4KKRIBF_-1_wxWfwndCM5MvLoPm_8vORX0MEYv1zJ0QLdu6Fv7FPHflolcmBsNOg1KlRf6QXZ
t_KPc1EM_PTYe63TfsIWddtpMLFNPj_yzewhia_AG3txv0pKiq_FG3txz0pKisy-0zVdz6hsSTpf9M0V6AYMSYBwDVP3oHwzIZhtw6MIjSVrsNTz1keNuR-R
VR-VWJLZ_UtObLrQxMc5mB-OVLHf_UiJ45h_-WJKelMlJq1k0lzYzb4Xy2zc7rK2_sBsKJ_tN-4UTsk7k-yDc-7kSINsKNRkVsMEdfLoxJStHq6jXvTRtMvl
3xYC1y6t_x_cRI_77FPHwvd_bNSiOgKWH7j1zfURUMBA3yy_ZvVOdiLTR_QsDejzbD_rNmidI5Rousrjjvk2PcRDzwwoXTNY45NP4MGSYz4lW6pQ-HlwBqE7
qF-_YWwZHC7sZw7A_qBTelybIFJ8NhkRw1S76L_pNdkcHl-9mBxdFnd1BEWbn-FFTl3ckvkzZGlXXfyci8-oM_-1SN7F_uQUobxW2DNWJqH00B_htkE81YZR
9AtqxprQp_opJzOx1TcxaDLsuyMnbtkhWWPGcoO_-CUOFl6_ybbPBo0cMQtXrfY62l2Cja25AK84np3jnuUg6oEg1iUOqKUY6U8ECO-nGFRDr8Sr6wPzX0d7
9fui2k1tQ8_20GWmxun-tg0f37H4mnVzRqV_oR1WjLwACNRUaFFPHmRwVcFtdEo_UlZJef_HhqsN_-_W4Vq_ZV_y9Fuv_cC0d85-A9gk_D_1umPupB_yX7-z
R3dTVg_tXyPy5UR_7yr_-MZ-Cyp_FXp7gVyUUQIVjvV8TWTeW6-jV_8BwvzglP-taO1eEB1lkcnt46Y0Bwv_wVzy_RiSjySn4B234x1ybRBlDFoR-n_w7_S_
_Ti5sryIS9WOJE2V3V3r_I-9n_rl3lj_xsC4ZvqS50B_Q80lvZ_eVyn_CF_3R1Wl4R2F_f43-6h-Y_x7_5TtJBznszakOD_PtHcti_pdSfB_X93_vE1d1em_
gzZ7_gG6cnNkJh_Kr_FVzBjAsDULN_4_ITkG1XIeTFuDzFCcaSdy1-YNJQH5vT-EqLTDfktr_gigE3bQqobUvvzk3UpJgKJ-4-mJIk7VjfAoZmnKgffSc_Pe
jrwXFUAZLscF-EYbFTwerw9bdrwhrhvUYzQ-NlPY27hJIJy6qje5jSHh8dzhrvKjSsNMdjTRRxtrrbjl_GK
}

!define KubeProxy(alias) KubeProxy(alias,"")
!define KubeProxy(alias, label)  KubernetesEntity(alias, "\nlabel", $kproxy,  KubeProxy)
