!include ../style.iuml

sprite $kubelet [256x248/16z] {
xDO7RW0W28LXfiBz3zn5cjNTKYFYTm8VPlomt7LTrtNX4sYAfmVJXZTG3y6ex_fW36qCVrUF2-3m3ydvwwT_IXkixte1Cl-MWNtNXtdS1JZMDxq0-yzDWaE8
_uvHi_K7Hg7w7t7jq4qWfKEtwmLmUY9jl3veiTJBD_2yr3il2cDzrmkm9oWRXU8h61TOt-u2wajniTJB9utN1ocMUlcqMEhb6zXvVLoWOkhLZqBsVKpgl7vz
5ellnxXWwasPcHUejTuKi-k9wwIU2RmIypHI8_KcGyY_W1POJ_yQ4xeWzJBN1vgPKRZj-X7hArs0RTMpQEoNnPYtNX6-Wkffnbwj5-jNNi1mdznH26ilW7ly
lWdyZDWM1w3azUilOF0NZyHTMO8gCGWSThp_WT_cSucqfbMguy_iOnUXAX0I0aUFju0ra1-7NYnFQTmmyI8OW4LFwhUfIcdR0h7G0GI8dYrBEioOeF1Z_05R
Zh39dxHQW3_53-GzYPU_S6a8Yni9G33qwaeZ1SBuho040ooG3VJldV7iXlWlBfUhDHWH53RGlm5zfN_QNu-_c67ALV9ZPq1Sj6F3Se36NgqYEt1Da13eg_ph
u6UCI8q25ljNfMt0tsy1KF1RqQFmLmlW1I0RLZS0-8iIeieYYEN6ENx8efm3w5yCt8CVmqxmoa_-jE77g3EO_jQ77oDFZAK_By3ls1I8aEwbJ_5J0pzRKY21
nbSS1V-ximXX1S31yRLamH-CYqzeDVthItF0du8yNAT8_5yiBr_mfs9BCm6CVkABxJHd_4MVbmk07LHXuD2VABAtNW0IHF_weXywudIjBAN_-bsO3gG_uBKu
1L0C_SLoh7JLcb3OVZhXy4S_iqZZLQMBn4iXPFwKA9NgLbOfrRx13TWUeEnp0qEbGDIQMf2_tWTedwubCoe5acPXhUDxIfDQ2A_-WHS0VFBZnWyOurp-YxFM
_gExU8wLS5BdLW6WLSbF32M-TBcM_y_uBmOXZV5JRXK0nU3VATCNO7oR2IxuxoS5ldS5RgtGnghe9uOJ3vOFjjEX62Yb60XBWV39JsKf3uzSOYqRVncJ0hN-
Ly7YnwT0-EXdXDI07v020Q8V47wy06Y3JPlmzme08FbHBFvU0M10z8F5toi01gZyWF43KY1avGUF7vy2UPD7pV5dmQzJ_FWKg3-aqDp4Rmt5G40AX0WfhU9t
QYW60b8WXgofa5yCjWrFH_mfowf01bfKvxZWtuH7TeVV5bQ14bPLbJpZJsqe1W9I87pXM_8FVcie1k9I849NlgYX60WG0FYsDrR5z6ZfnHyW-OiFAyL7fq2W
5LLkEP2DJu4897_IS1ZrY1H8GF9dWFuq205maFp5_40-YJ3-d1BrsT8_uQZIlyDioLk_Kh-DJO7myiVr2NDx87PaAFWKY7lbZ_vW3VSztaE5KoiY8EkLFn_g
tImQJzM3otTNf43PcqpNULTo-4u3_jOKg7SrbJVUbFBg_k9M5NBfHZXgpYLpGodfuZmsp8THH4NJwU2DSDgyba2nuTHsXcb3G625LLx21Nm459Z5PArETdCr
VUXo4LGiTzX6k9Q9j5A0oxVodcfrQvpw9CR0H43KeYFrqQYErkEOkJ3z3O4jFYbPIKyA983aLoh-F8jdrfr-jTC3M03mnLIfCyL_tQConhNP81yQ0I7EL5kX
YbmQ5klJUTIXfs7boEsKMMmLryV8OOghUFJO58W1yX_bb_McGp4CSVK0z540_8dAADRIEmlcCCJ5RmBLgeKw6XxOMyEIKbev2Rs2AE_WjvPs2FszfcbWZ4SE
1BAN0XVx_LzR6dKGeAk6FsaLmQfbXAllAAfHIq-xfzWd_w7CbezkmpOJ-BrpB6KF_e3qbnKUcsVRFLjfuZkfrALzyzWDt5WfBv1bc4DchCu8eudsjJmtWLlh
wSNrxEsrsEZJlkU65t1hERhyWHV-J6MDkXlKjlKwZJS9uBtuATiwmi6RAvA7w-1eyJN-wBidutJObHkMUzXJTBBpVkMO40dTN8nOStyjHlgRSpV-h_oylQJC
zCA4cH7DkMcM_E0FmDE305PqIR1x2NX2VuW6LlRIovyohZknJQ8VY0PMWVDNm-_8k-KtnHQjWPM_F547sCK4lTRCJykMIS_5dzjotha0hBXg90VnhEueo3jP
P88Vhu7sV4kKpkQLw7tUYX-lWLQQlXSoAaJxgiDM_7WDrDe8e_v40De7mvzVR5eCfSr6AJJHFfJ_upNmzbT-sHkPkKjLA07t10RWV-wXlvSh84E898j9cn_r
n7N2WMjWXM4rrnj0yaJx-X90_6rB5KXAtIarm9I9zZNcRB7sjYKhms8P3D6-RSUYjLVEQHaMw5ry2UELVeNVfwA1usckl89NTk5tv5ryjFBEGIuF1hoACQ1t
ckSNXpXeOYFi0zfA3HGr9RJsJOmSIpKGhdrpWShVxPs7igim34HN5hBr_p_yEXh4SpHaWX7ESAQaxIt7XBLJoUp061dOVGPb7dKpeVjkrO6ftPVVWGdTDqq7
jW7B_bjrOCAwBxC3yxjlVDVe1DqtTBph1DsNq87ftPVUWVdTbz-1-TsNtu7vtJU-0_apHdTVlD_baz1zhWEpoPo8laQ_PdPFFfewz-H32MkFkRlFqE_llfZl
xhxlxq0TjFwMu87P9t6ZdLC_-9Wwit_1v-Xj_QjbXZu1CQr_nIcKIVqL9x7CwO_Jg3Fw5vo7pkU_u4nEyjSgKbl7LknwvnzbOl-AKw7Gd_yzJSz-f0WestZZ
tW4HxMgGxFp3JDZHYfFXm9_NBosA_Ukh0-3387N-KIRsn-d8AtyjzlT3Vx7lk7K3mFXDOIQJC_ymGuJVq1_OwnFEf_NzbUpU4VkRqBB-DhiWVY3DFyY4-pzZ
15t_Pbipzjyw2wnGchlJimcPVpyJ-rSCWJh-rUqQiV_YfkPcFz5SQnNlty-4_Ws3uF_ynQ-EOd-_WNYLuLqNUlz-9lJ7CCJx-pqvzlSE06XdO4RD-_SpWJzX
76thNzTf_vY_xDQcwxRKpgh7paMPlZzZ9Bgji7NQF-PVTq5zyS-AimmoNN_1KCZz6Jyf7lUtRLeE-9Tt_1i6moQ4OWFmaJ_jSFv1fkkFuOW9DMl_j_rvuny-
_WioFN_2U9hvk-cluu-m_sngZ_rz9lPdN87svlzELIl2-S_69VJtcTXVS0ba_du0x5gxT6ZzGu7_iOnTl0ZUcDRj05ItoYM4wryx9u5Rd74tA2v3pDy_0j3j
4e610uz_zXMgrVa76IkOwxhFQEPl0s3ErEmp_KSV_xAkOWpU-0SPKrwQ_iPrttZCtm-0uZTK_iZB6yz_K64k1C3vHnbVU4LmBURldmEeCEJWyry2n-ByWuoR
y0hI_Fq0j6A7kzpxssraOlklVwUbxVgldp4Q4n8mtJthSzpw-ZPfdIQlieWqzTSUpr3cvi-d80EzYxuW1Rg9VaCIvHRwYZIME_WJygYJTz_y7IZ89RtxaYaJ
Tz_y7KZ8fqxQVVDtu89xaAHVSHDARlVbmxdw-PHS_Nn8vrdspRyFDC8DAVKIULrmNwYCXGYVy_3myF3my1C
}

!define Kublet(alias) Kublet(alias,"")
!define Kublet(alias, label)  KubernetesEntity(alias, "\nlabel", $kubelet,  Kublet)
