!include ../style.iuml


sprite $sched [256x248/16z] {
xDQ7GSH034JH3Ohz5qm6aS5vRxIlWz6TxLzEDqtJD4trGKcggpypJdW3zlUivLmVh9SqnB-Lum9L_4U4lrxzLvnsFVu5clc_ICsvFYZS1NgiJtY1xijfAo38
rx6MR3rW5B9lrC52Tpa22ztb22prbkEawmE3fTvoKl5I3oiAOttM2tG_cZM8rCEAmbYVzWBif-fWgRSS9LqV22prbcEmr5jEQixrGIfYweqVXTt7eItd-c1j
qDG3Z4BsCLbFkZvqiDHRZi1IRpbEkZxmpQIUaXuLXUElDwx7lLAa3XwwHf4JDd8ML_FzQI_Xg0l8gArttzwLA2qCiy02uV3z7_Y_VusLQcmtnSvypEaniKjW
ELg9yqasHkNfpdYrmZEea7vkzustMTP_JG5yCYspmLtW47vqOaAVsLP_A1dIYUZn6i1xGD4-aFw60GWosHaLV4Am6xz3qPTfWFVYBsxBjAXr02hP-ruaAaEW
5A7lHRoE0BmCVI_iLH4GXBvU0mtW_WNeOMcnx_jH5Ffw3Q2INpnwM5A89u10eQ_NW2mx18Q-NWC6S7y0-ZeDdDJvqMM-a9w3Ft3ewpN0yzt_p246fDEtXdxx
AIIAoIMGd7NVdPkSq9YU-zUjs8_Ua_oKyE69fhg_7hozuAltGj3ytARYvwFzvU3LKmO6_c-XJyr-00qc4_htpzurOhK4e3ZbZiUO-CQdQ2e1n07dmlnAO0b0
Jd5_e9K5bW2inFt7ammtjSJ-YmYWeTq_5rhT4wSMumvB4_7xINLF5_nMLgte381BtJyNIiod3Izgqt8qEiVz5ybuJaSNRTDA89da_XbKpfqFNm8WYX-y-zi6
BdoBWYQvly2slpS0Wj-WQvFmqv7YBxO-QF0x53ud-ub3oPzj_RxF8W2qNktGhNtT33-29u3IuYTttMtyGMW2aD_9Vkps4Vyj64m0zZlPJxmb9HarBG4GG4dn
us-lIIVrG7wd-B74AJF-cLC2rMS_BR6VpFwee0IY4x8VIk97ybbKb41oHlPZsnRaFMCN4801Oug6c-I_4ha2oBzosC0RAx2eqEr0tlUxZF8dFWtT0sddPZyq
u2JQt_reaVnx2KW0FhtrI-dcq3Tq4ut_lP3mXATq9j_vqMTR7ljPsGvI5ILGx8-e_kJjCgfstyud2agW_UjPrysdviD1aWSO2bu2uRCVsPqaFFcJD9dua3wM
K6Dm9xPqRN4BxcrO5bi5H706XFKd6zo9zYuxw3MtI19NeINGnEp7l_iVijuNaOS-FGaiPvP0T42Rr2DM9cBHMC79DFtG775E6JW22EXgMrmSyk2JsCg1eziJ
LZDJVcoc5H607L4ctoy-AMXS_osSyIM_Qb-ACg1ZqJJtCSzTXXzwvC6CQNu9T6ojbQzd5EtfszvQqyWqUsu9n8U22MrOcEG6s0OqUt89f8UMQbiHnjEKcG7u
mGGG-qofXyaVJBIDuDUY4cXdBj6Z_1IZP2JMHaq9H4VeJzxmIseq_cxjaXAexQS_zdVgZIunIduih3MHPf6Q2P-M0VdUXIJUnvTx4fXrXvGUK7JbNMB9cjDA
eBsHb1FFpH83Zd-7UdfoMgKjRtuy4QhG30XaI9epq6Q8Zlj6XNcN-etCcYFaNI0GaKYENxOOkYNNwJGsQB4XCo2G7L6-0RxbeFHABp7AGmRDW33BR3cEvDiV
oVeq-kysXsP0AFhBBo0eDKz_fHSPjcY1FWW7SIFRvAoWZC_Y9KxPAAL7EoK3QaV223CHPyqUUHWx-N0laXBqU0B0fn6s6lB7_hJTuhaPZZyXXhXqWIenl-um
RMgnqbYla3Paqcr22QGpq-Zub7ZeK4v3YP70202mXkz8nkGfM0oPj9pN0t9C5aaVAJClbFFBeIcZgXWmy427kDZDOgqo6i9lN-1Nm40eGWsLUHboBB7IEXf_
Gqo44z1K8NhDRyWxVNs7N-PCgjco8G05SFPnSwNLDsA8_spEV6w2Z3koj_ZvWxUEfNI2vRxjLM63vU93WAGXP3pQ2LNCH3Y6ZHQbXBcoKia6OKMRCA0Rj4ui
gKXJ-ZovPpoZL_YGFW9DU_C3SujqtAeDVJO18zm_1p7Er3JUYINmY5A53RkK_JUgV9pJ2Ns-F6xMBUr_Ki66EHr-E05Eap6ClmrwJ_icqy0GmFpnghcJsPXL
4_nS5admJ-T0Uvtq4xmrxJSQBTnyymSSUSstGo9V1G2Jvpkc_98yzPP1JGN4VRrOWdy-1v9QUmKGAlJl3qLzsAdQhG0_W0D7Tv0mDI_U_dCnyFWhdNqcLGFF
UbVi-2iPgNc1yKygZfwKlQlPxR3WpxeW97vSpPkBuoqg3jb_k4ToVRCEfU89XttOVlvpNfV7DFKylfZYKstlZ4rB7WgRo7svTW5gbNtc7rc6F97xSkNIsUSD
Uc8tX7r88HUVTzxDBloPKSGyxek9nxtPZl2dYHK6exblX5hzN0wKIBQZlMC_XvuHNi-1OcwqDd7X4xWl5yAP5rxmt5VFWRaKS5yH1-PIm7re3iIBuzF-UWuS
5qLoNoK7rdFVV9w9Qt4VNjTs0Uwhuy1wxgldm7hkg-V0Ukwhvy1wxgldm7hkA-W7bd3VzJXGRrKRKSI1UEwpCjw9Yt4VdWFbc4If4TgjMWguB-70EgaEGfU7
RvNyKozH6tzoqQDP3Grlp79OxChuUJakSIty-0JyilYjilwinn-b_OTw_0jCx8huUS59N0j_pdtpEJ1CcwgzOFDk64AFtrGrKOHhlqY_kfgd-EStuByx0P-j
GoFTSGST_cXfXyCbF-G-vFxs0FvOm2BV-HldTjWU-9twjTElKwJzMnd0ly15HtfT92B2h_y29XQc9_pslw4ngxNblzeJeRi2ElZqtyNRH_nq-lrdxmTtkKY_
dV9V6A5qntz77TBJIrkT6i8z8ExF5s10tn79WIsD4hwAdl70Jz5PY7LAZ1w5FHYJdaoA0To7v419F-VKSVH9A_vW07aoitZ0fFw3-83VbqaY7qmkPM7Aupyd
qJmIBknLrFyM0xWFoO4jovDrzMR-DYyBtUtMLdRiTy9yVfy1t8VXmDueDLwCmdFyzlojb4Fy_z-Jvm_Y7NvPPafyoZT9D9wk9SRnovR9ySgvtk3NPQhGo0rs
jex-jlB_13yFuEyO0y1zK0uClGFWs8kVLhA97y1z-3mmh75d9zpP_o3-PD7S_a7SXxyV7NfNKyv_EVxjh-Vy1-0-B0ScyIcDVzluDJMlyVYdoob28vqdolEV
RVpRNy_p7nptuMjXwWb01_7dNn_CV_kIluG3DPBjIkkV77_wzLjOaZ5pZf-MyyIJNnVhoo_higBMrxyv_gHSleN98iFrhondIgJQ9n5XwbmaxN_a-7iKnDqw
dMzpr_yeuBxn0KMIDRG-u4znjC7-bv-8FRK_RxpEV_F-Puu_7NTCpRVxdqNSr-zCskPMYwoXtRsVIBQEHzh_BiZxSl5BFkA3vy1wqQL4w4VW-r8aVBb7VF0S
M2-qr8bTdFkkpu6wr4evznKBNvZxhi-1jDIBNPJxhi-1RVaDgNsqkrwubllgHMhXrmlNmgyNYkkaVTVt0QVb1uNj7Cjlo-yAyLmXnCx_oP_yoP_yoP_y4m
}

!define Scheduler(alias) Scheduler(alias,"")
!define Scheduler(alias, label)  KubernetesEntity(alias, "\nlabel", $sched,  Scheduler)
