!include ./style.iuml
' Based on 
' - https://cncf-branding.netlify.app/projects/kubernetes/
sprite $kubernetes [256x256/16z] {
xC610000082W_QaNgG80001WSim3MM0GX882Ad3_0_-Uztl76P4zGVQPifDr40ipjPh8z4Ti59oWcxzWSgi4TN-BSXtxuH-XKjGUc9nlFntKMu2dVuVrS-tL
VqIdelRWl20Gs5TSGCn_pUIpKg_e0lGB-zEY4A5RT04Q_dzK2jhdZqAU7eVrilPOW7AbNZoTpakzyw9Gp1SogAWzc9mWT2ikWD1TZtAkq8r79LVgnMDIrnuB
v4yzjTnPpFE_9qWp80fpXYwr1qP04cKCNToz5X252LEFq4q1MPmmTDk598f2X6wiVv85a7eR-GFb5B4J__m3bKofX-EQIQAGfaU2IpKFnFhczW0Nwc3Z1Rf7
CwzXC_mWc1wENHNjySZ6-W2Vl-q76Bu2mfEr06vnYEVpjnQ7BVKVleGUUFmP_Rr5OJdzfSL0xfcUVp0tl_t7wdst_FO3RHViQ-2j7_znIzrv85Uhys1urFNj
Vy5_lJN1I4P-ERbCpvo0rHvBCjX_Fk5d0W3fdXds5-kO9qJ3FpByGuMkrCpgFp85igEotySaQm0ccDaLnuINpdX8_6S1uFqNk4Zpvm20OOr9_0jqWU_xP2Ic
DKzUtzUiU3Ww-mckcyB1c8PZK3qxCJRyivuYKq3hozwPdXMR_KW92KCb7zQQdnoR_L11oM1KrzsQWC9cFuMUSFcdjoq4BNxeRfx8Knr8YjMyLjjVeCMFtemZ
wEQkhEP_c-rDgE-4KLW8mf_QlRH57fB_Jzh-JSkkr4f2OgCyIK3uBtrSQhsBNoc8oYnPLferR0aKMrrcpjjvbstXcLIdodofMGvm2RIvraY-5fzZhRZ6-Ytb
jtIAh1wUuOiVfx-EYJXr8NqXVw41-lfNnPT0UcYfXVp-Vt9_ykHcZOnl_TR3rIemi_2g0iom4kZ8QXj5EQxOh9mu1mF3j7vzCuNWsi_iH4lMtshznfwZSkD7
GKKuWG5WymLdRoKcjiCLUgq9dDDk6yLswbpZYzzg0jEWtLmwKDEZawODUNklzKiR1Edzp6cy79l0xAVMDCL4VYcy4Wk0EA9eQ_oO1_Z70U3GSpYVoMy5bj40
u6EBBLxzchTIQXaC31V-l9L8UH7JVZ0m4SLFCU0IWtOllvpqJCQ7V_qGlGtA0dmp1z0NiX-lSP8tOzeSBx_m8fmCpE-N8jXQnZBdJneu0BxuoQ-giqAbifhI
RE4xFZ0EmOiV_VQlVez1MYXRbkxEp-4ayF2dxyRnEmpwzTESrcuJpxtJqDcFNmLdqB8DRfT_JhcTEVZny1AT_SZbq98Mgtzq-MSgEEIByCG081xVtuyk0NlH
Ca5bG8_TdmhoF3U3FGu0nOQ_B0mpLW35Eeon9P0-Tlyys7_FecUEou3yALu9s7-pnoaGlnR-Ucm5GWf58m0mltaKVQnH1FB0HB3YfnvLFb20rPe60i2Uue-B
TPpP07mmHbpnqt4SFeFVnpugkF2Fbb5uAdxjQlCIQ7xhwASWvF-_T46VIek4Au7qCVut8Z2MlcazDyRrGE9fQ55_0BQE3PlfUXv_lwRormweD_EZD6CDbG7n
Oyro5y1y2mTlvJ61Ae7qkFmfYyfcWMVDXXIEQWBxKFxwgqSfySnMBfiQ2W2_3ihlGeq4mxkVGjRopm50f-HFvIB1BDCpjZmalqEAdxNyBjGFCIw-Y5tuFmO0
DfO_bVSGMyv8bj_bTz1xCFbSVYeClvp_weiqllmm1k-dW5vx8-jYzX6RM5zu4OvVsMY8Oxb_AyXF4_VQsqW3IYzzcK-O3Gzyj7ksqciRap14hJPPvEBP2SA8
G6K0LL5N05w4at_I9losnS2pt_o4rHCz_Y9HpvC0o49iLs6cJSc9rKoRKHskJBjg86Rrd0E0ogyTzoMFYpvFcNo7ATFPVTbz6lwn9xbO5FzVFBxGmYwzSrhy
q8xazGrg-knhGOVZpwdvAIO4ykdZUJPPqswcIriQhCstytYYWG2b-cf-aFoNkCP2XGXz2rBNUKJ-oxfqeQC0q7O5GHhN4mkDaaLlAYyN-weL0jIFx_aF-rgl
Dk4lzvJ7Yng4XnbGTcfTrhoxBuqAa2pCVwtZKEgSooBZdeARbs2nflUHXKit0gKiKgDEXEVoTqIZ7Zxv6geTymjgHyHuU6Djs92ldwKj1F6HOGfgjy-itIXN
gMvd1hCpcp8IRBTNAGSegr2psWVpq9wakDr-i_GZMdAEIXlm6VCRSBThBKnaQqLxrO6qG-Pdu7wdIVUEn3SEmlVE4uTYDA3RdTkj8cDZ_OlkNnzDw8ReTEhs
UaS_lsLZzEwBMQZXK-wbQppoFJtbHdo2xmQifuuSiJuTTUdYSYW-a_0d7j1I0LGHZ1Oca5F6OS2wIkbYUZt3PHMSj1erZVCpA0DjaKzoRKEwSC7amZAeHMe-
fcRERtYZHdN8rn-E68nzi30Z_qetw_ndNjbCSUmhD3rvb5vq1qeRQSgvueoHQykr0Yv2kuuTmWGbde7n52tv5fJHUU1JlrA8-FxwoJVnyAQ943_f_QDlWee6
wxO3SCvpKZm3QwLpF79L_WLW7uA1zPH3OfTt3MF0uRlsiTDlj7X1mECtDMIu2cEEeF8Fdlxb13h_e7_bHu__Ilxq-MlquVE_37xgEFxTJCeFdaSl2JW15y10
4808_6Xy10uHuDZ3p_0Cb8_1X_37l-DZ4A1u30Dh-PdQJwEwMi2px_22EpKFm2I9lv1B0Um3CB1E02H-_nJu_boe-F91L2BPXsSWNG0aJ9YkAeAy25y5blnu
1kewV3BSz7-N-TqB7mcUTFjNFYy_uZc_1SO-V38cDJrhtJc8VNW6UY52pua9pRx-fSyeHBCfJ23impEGXvCupPxwQGRQD8cJ8lkSi0_Fm2p_fyyn0R0FpK2T
by-5sqtOXsVWWUAHAnNMxCCpi7R40zr30h0FsvEmmdQRFWHW7vQ1NgXhSmO0D9l1pG2gVzoVGnJ0FZ03hJH__oO4O1-SWKxbSczzsNzl8lzknqwo60X180oN
61gy_uMpP9avy5xLTuDkzNVue7sT3OmhpySovxIlh3oZEFxCpYI1qj30RjM-ZWRsCtI8CyH68MoWeubnjg_SEDjNdBDz9SQqZxE1ZcR6sRwoETjNdBDz9ThR
nzb0Ho5iu8KnTclxE1kuC4cqjO-pWOvXhATzd0qCWFa7nC94bWHhl_qzA0o3xJY_b6wOpcp_Y2qyIKH4H4H4H4H4H4Jk
}





!define Kubernetes(alias) Kubernetes(alias,"")
!define Kubernetes(alias, label)  KubernetesEntity(alias, "\nlabel", $kubernetes,  Kubernetes)
